ncinpathbase: 'LANDMODEL/WY'
ncoutpathbase: 'LANDMODEL/DAILY/'
ncoutfnamebase: 'landmodel_output_daily_wy'

wrfvars:
    - 'SMOIS'
    - 'SFROFF'
    - 'SNOW'
    - 'SNOWH'
    - 'TSLB'
    - 'LH'
    - 'GHV'
    - 'GHB'
    - 'EVG'
    - 'EVB'
    - 'SHG'
    - 'SHC'
    - 'SHB'
    - 'FVEG'
wrfoutvars:
    - 'SMOIS_DM'
    - 'SFROFF_DV'
    - 'SNOW_DM'
    - 'SNOWH_DM'
    - 'TSLB_DM'
    - 'LH_DM'
    - 'GHV_DM'
    - 'GHB_DM'
    - 'EVG_DM'
    - 'EVB_DM'
    - 'SHG_DM'
    - 'SHC_DM'
    - 'SHB_DM'
    - 'FVEG_DM'
wrfoperators:
    - 'mean'
    - 'sum'
    - 'mean'
    - 'mean'
    - 'mean'
    - 'mean'
    - 'mean'
    - 'mean'
    - 'mean'
    - 'mean'
    - 'mean'
    - 'mean'
    - 'mean'
    - 'mean'
wrfdescriptions:
    - 'Soil moisture, daily average'
    - 'Surface runoff, daily total'
    - 'Snow water equivalent, daily average'
    - 'Physical snow depth, daily average'
    - 'Soil temperature, daily average'
    - 'Latent heat flux at the surface, daily average'
    - 'Heat flux into soil: under canopy, daily average'
    - 'Heat flux into soil: bare fraction, daily average'
    - 'Latent heat flux: ground to canopy, daily average'
    - 'Latent heat flux: bare grnd to canopy, daily average'
    - 'Sensible heat flux: ground to canopy, daily average'
    - 'Sensible heat flux: leaf to canopy, daily average'
    - 'Sensible heat flux: bare grnd to atmo, daily average'
    - 'Noah-MP vegetation fraction'
wrfunits:
    - 'm3 m-3'
    - 'mm'
    - 'kg m-2'
    - 'm'
    - 'K'
    - 'W m-2'
    - 'W m-2'
    - 'W m-2'
    - 'W m-2'
    - 'W m-2'
    - 'W m-2'
    - 'W m-2'
    - 'W m-2'
    - ''
